// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveAccountByID = `-- name: FindActiveAccountByID :one
SELECT id, account_id, username, email, mobile, password, nickname, icon,
       type, status, gmt_create, gmt_modified, gmt_last_login, creator, modifier, tenant_id
FROM account
WHERE account_id = $1 AND status <> 0
LIMIT 1
`

func (q *Queries) FindActiveAccountByID(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRow(ctx, findActiveAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Icon,
		&i.Type,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.GmtLastLogin,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveAccountByUsername = `-- name: FindActiveAccountByUsername :one
SELECT id, account_id, username, email, mobile, password, nickname, icon,
       type, status, gmt_create, gmt_modified, gmt_last_login, creator, modifier, tenant_id
FROM account
WHERE username = $1 AND status <> 0
LIMIT 1
`

func (q *Queries) FindActiveAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, findActiveAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Icon,
		&i.Type,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.GmtLastLogin,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const updateAccountLastLogin = `-- name: UpdateAccountLastLogin :exec
UPDATE account
SET gmt_last_login = $2,
    gmt_modified = CURRENT_TIMESTAMP
WHERE account_id = $1 AND status <> 0
`

type UpdateAccountLastLoginParams struct {
	AccountID    string           `json:"account_id"`
	GmtLastLogin pgtype.Timestamp `json:"gmt_last_login"`
}

func (q *Queries) UpdateAccountLastLogin(ctx context.Context, arg UpdateAccountLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateAccountLastLogin, arg.AccountID, arg.GmtLastLogin)
	return err
}
