// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_schema.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentSchema = `-- name: CreateAgentSchema :one
INSERT INTO agent_schema (
    agent_id, workspace_id, name, description, type, instruction, input_keys, output_key,
    handle, sub_agents, yaml_schema, status, enabled, gmt_create, gmt_modified, creator, modifier, tenant_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id
`

type CreateAgentSchemaParams struct {
	AgentID     pgtype.Text      `json:"agent_id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Type        string           `json:"type"`
	Instruction pgtype.Text      `json:"instruction"`
	InputKeys   pgtype.Text      `json:"input_keys"`
	OutputKey   pgtype.Text      `json:"output_key"`
	Handle      pgtype.Text      `json:"handle"`
	SubAgents   pgtype.Text      `json:"sub_agents"`
	YamlSchema  pgtype.Text      `json:"yaml_schema"`
	Status      string           `json:"status"`
	Enabled     int16            `json:"enabled"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateAgentSchema(ctx context.Context, arg CreateAgentSchemaParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAgentSchema,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Instruction,
		arg.InputKeys,
		arg.OutputKey,
		arg.Handle,
		arg.SubAgents,
		arg.YamlSchema,
		arg.Status,
		arg.Enabled,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAgentSchema = `-- name: DeleteAgentSchema :exec
DELETE FROM agent_schema WHERE id = $1 AND workspace_id = $2
`

type DeleteAgentSchemaParams struct {
	ID          int64  `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteAgentSchema(ctx context.Context, arg DeleteAgentSchemaParams) error {
	_, err := q.db.Exec(ctx, deleteAgentSchema, arg.ID, arg.WorkspaceID)
	return err
}

const findAgentSchemaByIDAndWorkspace = `-- name: FindAgentSchemaByIDAndWorkspace :one
SELECT id, agent_id, workspace_id, name, description, type, instruction, input_keys, output_key,
       handle, sub_agents, yaml_schema, status, enabled, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM agent_schema
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type FindAgentSchemaByIDAndWorkspaceParams struct {
	ID          int64  `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindAgentSchemaByIDAndWorkspace(ctx context.Context, arg FindAgentSchemaByIDAndWorkspaceParams) (AgentSchema, error) {
	row := q.db.QueryRow(ctx, findAgentSchemaByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i AgentSchema
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Instruction,
		&i.InputKeys,
		&i.OutputKey,
		&i.Handle,
		&i.SubAgents,
		&i.YamlSchema,
		&i.Status,
		&i.Enabled,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findAgentSchemaByNameAndWorkspace = `-- name: FindAgentSchemaByNameAndWorkspace :one
SELECT id, agent_id, workspace_id, name, description, type, instruction, input_keys, output_key,
       handle, sub_agents, yaml_schema, status, enabled, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM agent_schema
WHERE name = $1 AND workspace_id = $2
LIMIT 1
`

type FindAgentSchemaByNameAndWorkspaceParams struct {
	Name        string `json:"name"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindAgentSchemaByNameAndWorkspace(ctx context.Context, arg FindAgentSchemaByNameAndWorkspaceParams) (AgentSchema, error) {
	row := q.db.QueryRow(ctx, findAgentSchemaByNameAndWorkspace, arg.Name, arg.WorkspaceID)
	var i AgentSchema
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Instruction,
		&i.InputKeys,
		&i.OutputKey,
		&i.Handle,
		&i.SubAgents,
		&i.YamlSchema,
		&i.Status,
		&i.Enabled,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listAgentSchemasByWorkspace = `-- name: ListAgentSchemasByWorkspace :many
SELECT id, agent_id, workspace_id, name, description, type, instruction, input_keys, output_key,
       handle, sub_agents, yaml_schema, status, enabled, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM agent_schema
WHERE workspace_id = $1 AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
ORDER BY gmt_modified DESC
`

type ListAgentSchemasByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
}

func (q *Queries) ListAgentSchemasByWorkspace(ctx context.Context, arg ListAgentSchemasByWorkspaceParams) ([]AgentSchema, error) {
	rows, err := q.db.Query(ctx, listAgentSchemasByWorkspace, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSchema
	for rows.Next() {
		var i AgentSchema
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Instruction,
			&i.InputKeys,
			&i.OutputKey,
			&i.Handle,
			&i.SubAgents,
			&i.YamlSchema,
			&i.Status,
			&i.Enabled,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSchema = `-- name: UpdateAgentSchema :exec
UPDATE agent_schema
SET name = $3, description = $4, type = $5, instruction = $6, input_keys = $7, output_key = $8,
    handle = $9, sub_agents = $10, yaml_schema = $11, status = $12, enabled = $13,
    gmt_modified = $14, modifier = $15
WHERE id = $1 AND workspace_id = $2
`

type UpdateAgentSchemaParams struct {
	ID          int64            `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Type        string           `json:"type"`
	Instruction pgtype.Text      `json:"instruction"`
	InputKeys   pgtype.Text      `json:"input_keys"`
	OutputKey   pgtype.Text      `json:"output_key"`
	Handle      pgtype.Text      `json:"handle"`
	SubAgents   pgtype.Text      `json:"sub_agents"`
	YamlSchema  pgtype.Text      `json:"yaml_schema"`
	Status      string           `json:"status"`
	Enabled     int16            `json:"enabled"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateAgentSchema(ctx context.Context, arg UpdateAgentSchemaParams) error {
	_, err := q.db.Exec(ctx, updateAgentSchema,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Instruction,
		arg.InputKeys,
		arg.OutputKey,
		arg.Handle,
		arg.SubAgents,
		arg.YamlSchema,
		arg.Status,
		arg.Enabled,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
