// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPIKeysByAccountID = `-- name: CountActiveAPIKeysByAccountID :one
SELECT COUNT(*)::bigint
FROM api_key
WHERE account_id = $1 AND status <> 0
`

func (q *Queries) CountActiveAPIKeysByAccountID(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeysByAccountID, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findActiveAPIKeyByEncryptedKey = `-- name: FindActiveAPIKeyByEncryptedKey :one
SELECT id, account_id, api_key, status, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM api_key
WHERE api_key = $1 AND status <> 0
LIMIT 1
`

type FindActiveAPIKeyByEncryptedKeyRow struct {
	ID          int64            `json:"id"`
	AccountID   string           `json:"account_id"`
	ApiKey      string           `json:"api_key"`
	Status      int16            `json:"status"`
	Description pgtype.Text      `json:"description"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) FindActiveAPIKeyByEncryptedKey(ctx context.Context, apiKey string) (FindActiveAPIKeyByEncryptedKeyRow, error) {
	row := q.db.QueryRow(ctx, findActiveAPIKeyByEncryptedKey, apiKey)
	var i FindActiveAPIKeyByEncryptedKeyRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ApiKey,
		&i.Status,
		&i.Description,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveAPIKeyByHash = `-- name: FindActiveAPIKeyByHash :one
SELECT id, account_id, api_key, status, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM api_key
WHERE api_key_hash = $1 AND status <> 0
LIMIT 1
`

type FindActiveAPIKeyByHashRow struct {
	ID          int64            `json:"id"`
	AccountID   string           `json:"account_id"`
	ApiKey      string           `json:"api_key"`
	Status      int16            `json:"status"`
	Description pgtype.Text      `json:"description"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) FindActiveAPIKeyByHash(ctx context.Context, apiKeyHash pgtype.Text) (FindActiveAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, findActiveAPIKeyByHash, apiKeyHash)
	var i FindActiveAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ApiKey,
		&i.Status,
		&i.Description,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActiveAPIKeysByAccountID = `-- name: ListActiveAPIKeysByAccountID :many
SELECT id, account_id, api_key, status, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM api_key
WHERE account_id = $1 AND status <> 0
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListActiveAPIKeysByAccountIDParams struct {
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListActiveAPIKeysByAccountIDRow struct {
	ID          int64            `json:"id"`
	AccountID   string           `json:"account_id"`
	ApiKey      string           `json:"api_key"`
	Status      int16            `json:"status"`
	Description pgtype.Text      `json:"description"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) ListActiveAPIKeysByAccountID(ctx context.Context, arg ListActiveAPIKeysByAccountIDParams) ([]ListActiveAPIKeysByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeysByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAPIKeysByAccountIDRow
	for rows.Next() {
		var i ListActiveAPIKeysByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ApiKey,
			&i.Status,
			&i.Description,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
