// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveApplicationVersions = `-- name: CountActiveApplicationVersions :one
SELECT COUNT(*)::bigint
FROM application_version
WHERE app_id = $1 AND workspace_id = $2
  AND ($3::smallint = -1 OR status = $3::smallint)
  AND status <> 0
`

type CountActiveApplicationVersionsParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
	Column3     int16  `json:"column_3"`
}

func (q *Queries) CountActiveApplicationVersions(ctx context.Context, arg CountActiveApplicationVersionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApplicationVersions, arg.AppID, arg.WorkspaceID, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveApplicationsByWorkspace = `-- name: CountActiveApplicationsByWorkspace :one
SELECT COUNT(*)::bigint
FROM application
WHERE workspace_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR type = $3::text)
  AND ($4::smallint = -1 OR status = $4::smallint)
  AND status <> 0
`

type CountActiveApplicationsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     string `json:"column_3"`
	Column4     int16  `json:"column_4"`
}

func (q *Queries) CountActiveApplicationsByWorkspace(ctx context.Context, arg CountActiveApplicationsByWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApplicationsByWorkspace,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createApplication = `-- name: CreateApplication :exec
INSERT INTO application (
    workspace_id, app_id, name, description, icon, source, type, status,
    gmt_create, gmt_modified, creator, modifier, tenant_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateApplicationParams struct {
	WorkspaceID string           `json:"workspace_id"`
	AppID       string           `json:"app_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Icon        pgtype.Text      `json:"icon"`
	Source      string           `json:"source"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.Exec(ctx, createApplication,
		arg.WorkspaceID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Source,
		arg.Type,
		arg.Status,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const createApplicationVersion = `-- name: CreateApplicationVersion :exec
INSERT INTO application_version (
    app_id, workspace_id, config, status, version, description,
    gmt_create, gmt_modified, creator, modifier, tenant_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateApplicationVersionParams struct {
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	Config      pgtype.Text      `json:"config"`
	Status      int16            `json:"status"`
	Version     string           `json:"version"`
	Description pgtype.Text      `json:"description"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateApplicationVersion(ctx context.Context, arg CreateApplicationVersionParams) error {
	_, err := q.db.Exec(ctx, createApplicationVersion,
		arg.AppID,
		arg.WorkspaceID,
		arg.Config,
		arg.Status,
		arg.Version,
		arg.Description,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const findActiveApplicationByIDAndWorkspace = `-- name: FindActiveApplicationByIDAndWorkspace :one
SELECT id, workspace_id, app_id, name, description, icon, source, type, status,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application
WHERE app_id = $1 AND workspace_id = $2 AND status <> 0
LIMIT 1
`

type FindActiveApplicationByIDAndWorkspaceParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindActiveApplicationByIDAndWorkspace(ctx context.Context, arg FindActiveApplicationByIDAndWorkspaceParams) (Application, error) {
	row := q.db.QueryRow(ctx, findActiveApplicationByIDAndWorkspace, arg.AppID, arg.WorkspaceID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Source,
		&i.Type,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveApplicationByNameAndWorkspace = `-- name: FindActiveApplicationByNameAndWorkspace :one
SELECT id, workspace_id, app_id, name, description, icon, source, type, status,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application
WHERE name = $1 AND workspace_id = $2 AND status <> 0
LIMIT 1
`

type FindActiveApplicationByNameAndWorkspaceParams struct {
	Name        string `json:"name"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindActiveApplicationByNameAndWorkspace(ctx context.Context, arg FindActiveApplicationByNameAndWorkspaceParams) (Application, error) {
	row := q.db.QueryRow(ctx, findActiveApplicationByNameAndWorkspace, arg.Name, arg.WorkspaceID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Source,
		&i.Type,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findApplicationVersionByVersion = `-- name: FindApplicationVersionByVersion :one
SELECT id, app_id, workspace_id, config, status, version, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application_version
WHERE app_id = $1 AND workspace_id = $2 AND version = $3 AND status <> 0
LIMIT 1
`

type FindApplicationVersionByVersionParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
	Version     string `json:"version"`
}

func (q *Queries) FindApplicationVersionByVersion(ctx context.Context, arg FindApplicationVersionByVersionParams) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, findApplicationVersionByVersion, arg.AppID, arg.WorkspaceID, arg.Version)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.Config,
		&i.Status,
		&i.Version,
		&i.Description,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findLastPublishedApplicationVersion = `-- name: FindLastPublishedApplicationVersion :one
SELECT id, app_id, workspace_id, config, status, version, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application_version
WHERE app_id = $1 AND workspace_id = $2 AND status = 2
ORDER BY id DESC
LIMIT 1
`

type FindLastPublishedApplicationVersionParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindLastPublishedApplicationVersion(ctx context.Context, arg FindLastPublishedApplicationVersionParams) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, findLastPublishedApplicationVersion, arg.AppID, arg.WorkspaceID)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.Config,
		&i.Status,
		&i.Version,
		&i.Description,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findLatestActiveApplicationVersion = `-- name: FindLatestActiveApplicationVersion :one
SELECT id, app_id, workspace_id, config, status, version, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application_version
WHERE app_id = $1 AND workspace_id = $2 AND status <> 0
ORDER BY id DESC
LIMIT 1
`

type FindLatestActiveApplicationVersionParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindLatestActiveApplicationVersion(ctx context.Context, arg FindLatestActiveApplicationVersionParams) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, findLatestActiveApplicationVersion, arg.AppID, arg.WorkspaceID)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.Config,
		&i.Status,
		&i.Version,
		&i.Description,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActiveApplicationVersions = `-- name: ListActiveApplicationVersions :many
SELECT id, app_id, workspace_id, config, status, version, description,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application_version
WHERE app_id = $1 AND workspace_id = $2
  AND ($3::smallint = -1 OR status = $3::smallint)
  AND status <> 0
ORDER BY id DESC
LIMIT $4 OFFSET $5
`

type ListActiveApplicationVersionsParams struct {
	AppID       string `json:"app_id"`
	WorkspaceID string `json:"workspace_id"`
	Column3     int16  `json:"column_3"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListActiveApplicationVersions(ctx context.Context, arg ListActiveApplicationVersionsParams) ([]ApplicationVersion, error) {
	rows, err := q.db.Query(ctx, listActiveApplicationVersions,
		arg.AppID,
		arg.WorkspaceID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationVersion
	for rows.Next() {
		var i ApplicationVersion
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.WorkspaceID,
			&i.Config,
			&i.Status,
			&i.Version,
			&i.Description,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveApplicationsByWorkspace = `-- name: ListActiveApplicationsByWorkspace :many
SELECT id, workspace_id, app_id, name, description, icon, source, type, status,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM application
WHERE workspace_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR type = $3::text)
  AND ($4::smallint = -1 OR status = $4::smallint)
  AND status <> 0
ORDER BY id DESC
LIMIT $5 OFFSET $6
`

type ListActiveApplicationsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     string `json:"column_3"`
	Column4     int16  `json:"column_4"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListActiveApplicationsByWorkspace(ctx context.Context, arg ListActiveApplicationsByWorkspaceParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listActiveApplicationsByWorkspace,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Source,
			&i.Type,
			&i.Status,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationDeleted = `-- name: MarkApplicationDeleted :exec
UPDATE application
SET status = 0, gmt_modified = $3, modifier = $4
WHERE app_id = $1 AND workspace_id = $2 AND status <> 0
`

type MarkApplicationDeletedParams struct {
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) MarkApplicationDeleted(ctx context.Context, arg MarkApplicationDeletedParams) error {
	_, err := q.db.Exec(ctx, markApplicationDeleted,
		arg.AppID,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const markApplicationVersionsDeleted = `-- name: MarkApplicationVersionsDeleted :exec
UPDATE application_version
SET status = 0, gmt_modified = $3, modifier = $4
WHERE app_id = $1 AND workspace_id = $2 AND status <> 0
`

type MarkApplicationVersionsDeletedParams struct {
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) MarkApplicationVersionsDeleted(ctx context.Context, arg MarkApplicationVersionsDeletedParams) error {
	_, err := q.db.Exec(ctx, markApplicationVersionsDeleted,
		arg.AppID,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE application
SET name = $3, description = $4, icon = $5, type = $6, status = $7,
    gmt_modified = $8, modifier = $9
WHERE app_id = $1 AND workspace_id = $2 AND status <> 0
`

type UpdateApplicationParams struct {
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Icon        pgtype.Text      `json:"icon"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.AppID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Type,
		arg.Status,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateApplicationVersion = `-- name: UpdateApplicationVersion :exec
UPDATE application_version
SET config = $4, status = $5, description = $6, gmt_modified = $7, modifier = $8
WHERE app_id = $1 AND workspace_id = $2 AND version = $3 AND status <> 0
`

type UpdateApplicationVersionParams struct {
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	Version     string           `json:"version"`
	Config      pgtype.Text      `json:"config"`
	Status      int16            `json:"status"`
	Description pgtype.Text      `json:"description"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateApplicationVersion(ctx context.Context, arg UpdateApplicationVersionParams) error {
	_, err := q.db.Exec(ctx, updateApplicationVersion,
		arg.AppID,
		arg.WorkspaceID,
		arg.Version,
		arg.Config,
		arg.Status,
		arg.Description,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
