// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_token_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTokenSession = `-- name: CreateTokenSession :exec
INSERT INTO auth_token_session (
  token_id, account_id, token_type, token_hash, expires_at,
  revoked, source, caller_ip, user_agent, tenant_id
) VALUES (
  $1, $2, $3, $4, $5,
  0, $6, $7, $8, $9
)
`

type CreateTokenSessionParams struct {
	TokenID   string           `json:"token_id"`
	AccountID string           `json:"account_id"`
	TokenType string           `json:"token_type"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Source    pgtype.Text      `json:"source"`
	CallerIp  pgtype.Text      `json:"caller_ip"`
	UserAgent pgtype.Text      `json:"user_agent"`
	TenantID  pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateTokenSession(ctx context.Context, arg CreateTokenSessionParams) error {
	_, err := q.db.Exec(ctx, createTokenSession,
		arg.TokenID,
		arg.AccountID,
		arg.TokenType,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Source,
		arg.CallerIp,
		arg.UserAgent,
		arg.TenantID,
	)
	return err
}

const deleteExpiredTokenSessions = `-- name: DeleteExpiredTokenSessions :exec
DELETE FROM auth_token_session
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredTokenSessions(ctx context.Context, expiresAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokenSessions, expiresAt)
	return err
}

const findActiveTokenSessionByHash = `-- name: FindActiveTokenSessionByHash :one
SELECT id, token_id, account_id, token_type, token_hash, expires_at, revoked,
       source, caller_ip, user_agent, gmt_create, gmt_modified, tenant_id
FROM auth_token_session
WHERE token_hash = $1
  AND token_type = $2
  AND revoked = 0
  AND expires_at > $3
LIMIT 1
`

type FindActiveTokenSessionByHashParams struct {
	TokenHash string           `json:"token_hash"`
	TokenType string           `json:"token_type"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) FindActiveTokenSessionByHash(ctx context.Context, arg FindActiveTokenSessionByHashParams) (AuthTokenSession, error) {
	row := q.db.QueryRow(ctx, findActiveTokenSessionByHash, arg.TokenHash, arg.TokenType, arg.ExpiresAt)
	var i AuthTokenSession
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.AccountID,
		&i.TokenType,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.Source,
		&i.CallerIp,
		&i.UserAgent,
		&i.GmtCreate,
		&i.GmtModified,
		&i.TenantID,
	)
	return i, err
}

const revokeAccountTokens = `-- name: RevokeAccountTokens :exec
UPDATE auth_token_session
SET revoked = 1,
    gmt_modified = CURRENT_TIMESTAMP
WHERE account_id = $1
  AND token_type = $2
  AND revoked = 0
`

type RevokeAccountTokensParams struct {
	AccountID string `json:"account_id"`
	TokenType string `json:"token_type"`
}

func (q *Queries) RevokeAccountTokens(ctx context.Context, arg RevokeAccountTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAccountTokens, arg.AccountID, arg.TokenType)
	return err
}

const revokeTokenSessionByHash = `-- name: RevokeTokenSessionByHash :exec
UPDATE auth_token_session
SET revoked = 1,
    gmt_modified = CURRENT_TIMESTAMP
WHERE token_hash = $1
`

func (q *Queries) RevokeTokenSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeTokenSessionByHash, tokenHash)
	return err
}
