// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: component.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationComponent = `-- name: CreateApplicationComponent :exec
INSERT INTO application_component (gmt_create,gmt_modified,code,name,workspace_id,type,app_id,config,description,status,creator,modifier,need_update,tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,0,$13)
`

type CreateApplicationComponentParams struct {
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Code        string           `json:"code"`
	Name        string           `json:"name"`
	WorkspaceID string           `json:"workspace_id"`
	Type        string           `json:"type"`
	AppID       pgtype.Text      `json:"app_id"`
	Config      pgtype.Text      `json:"config"`
	Description pgtype.Text      `json:"description"`
	Status      pgtype.Int2      `json:"status"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateApplicationComponent(ctx context.Context, arg CreateApplicationComponentParams) error {
	_, err := q.db.Exec(ctx, createApplicationComponent,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Code,
		arg.Name,
		arg.WorkspaceID,
		arg.Type,
		arg.AppID,
		arg.Config,
		arg.Description,
		arg.Status,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deleteApplicationComponent = `-- name: DeleteApplicationComponent :exec
UPDATE application_component SET status=0,gmt_modified=$3,modifier=$4
WHERE workspace_id=$1 AND code=$2 AND status<>0
`

type DeleteApplicationComponentParams struct {
	WorkspaceID string           `json:"workspace_id"`
	Code        string           `json:"code"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) DeleteApplicationComponent(ctx context.Context, arg DeleteApplicationComponentParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationComponent,
		arg.WorkspaceID,
		arg.Code,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const findActiveApplicationComponent = `-- name: FindActiveApplicationComponent :one
SELECT id,gmt_create,gmt_modified,code,name,workspace_id,type,app_id,config,description,status,creator,modifier,need_update,tenant_id
FROM application_component WHERE workspace_id=$1 AND code=$2 AND status<>0 LIMIT 1
`

type FindActiveApplicationComponentParams struct {
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
}

func (q *Queries) FindActiveApplicationComponent(ctx context.Context, arg FindActiveApplicationComponentParams) (ApplicationComponent, error) {
	row := q.db.QueryRow(ctx, findActiveApplicationComponent, arg.WorkspaceID, arg.Code)
	var i ApplicationComponent
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Code,
		&i.Name,
		&i.WorkspaceID,
		&i.Type,
		&i.AppID,
		&i.Config,
		&i.Description,
		&i.Status,
		&i.Creator,
		&i.Modifier,
		&i.NeedUpdate,
		&i.TenantID,
	)
	return i, err
}

const findActiveApplicationComponentByAppID = `-- name: FindActiveApplicationComponentByAppID :one
SELECT id,gmt_create,gmt_modified,code,name,workspace_id,type,app_id,config,description,status,creator,modifier,need_update,tenant_id
FROM application_component WHERE workspace_id=$1 AND app_id=$2 AND status<>0 LIMIT 1
`

type FindActiveApplicationComponentByAppIDParams struct {
	WorkspaceID string      `json:"workspace_id"`
	AppID       pgtype.Text `json:"app_id"`
}

func (q *Queries) FindActiveApplicationComponentByAppID(ctx context.Context, arg FindActiveApplicationComponentByAppIDParams) (ApplicationComponent, error) {
	row := q.db.QueryRow(ctx, findActiveApplicationComponentByAppID, arg.WorkspaceID, arg.AppID)
	var i ApplicationComponent
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Code,
		&i.Name,
		&i.WorkspaceID,
		&i.Type,
		&i.AppID,
		&i.Config,
		&i.Description,
		&i.Status,
		&i.Creator,
		&i.Modifier,
		&i.NeedUpdate,
		&i.TenantID,
	)
	return i, err
}

const listActiveApplicationComponents = `-- name: ListActiveApplicationComponents :many
SELECT id,gmt_create,gmt_modified,code,name,workspace_id,type,app_id,config,description,status,creator,modifier,need_update,tenant_id
FROM application_component
WHERE workspace_id=$1
  AND ($2::text='' OR name ILIKE '%' || $2::text || '%')
  AND ($3::text='' OR type=$3)
  AND ($4::text='' OR app_id=$4)
  AND ($5::smallint < 0 OR status=$5)
  AND status<>0
ORDER BY gmt_modified DESC
`

type ListActiveApplicationComponentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     string `json:"column_3"`
	Column4     string `json:"column_4"`
	Column5     int16  `json:"column_5"`
}

func (q *Queries) ListActiveApplicationComponents(ctx context.Context, arg ListActiveApplicationComponentsParams) ([]ApplicationComponent, error) {
	rows, err := q.db.Query(ctx, listActiveApplicationComponents,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationComponent
	for rows.Next() {
		var i ApplicationComponent
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Code,
			&i.Name,
			&i.WorkspaceID,
			&i.Type,
			&i.AppID,
			&i.Config,
			&i.Description,
			&i.Status,
			&i.Creator,
			&i.Modifier,
			&i.NeedUpdate,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationComponent = `-- name: UpdateApplicationComponent :exec
UPDATE application_component SET name=$3,type=$4,app_id=$5,config=$6,description=$7,status=$8,gmt_modified=$9,modifier=$10
WHERE workspace_id=$1 AND code=$2 AND status<>0
`

type UpdateApplicationComponentParams struct {
	WorkspaceID string           `json:"workspace_id"`
	Code        string           `json:"code"`
	Name        string           `json:"name"`
	Type        string           `json:"type"`
	AppID       pgtype.Text      `json:"app_id"`
	Config      pgtype.Text      `json:"config"`
	Description pgtype.Text      `json:"description"`
	Status      pgtype.Int2      `json:"status"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) UpdateApplicationComponent(ctx context.Context, arg UpdateApplicationComponentParams) error {
	_, err := q.db.Exec(ctx, updateApplicationComponent,
		arg.WorkspaceID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.AppID,
		arg.Config,
		arg.Description,
		arg.Status,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
