// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO document (workspace_id,kb_id,doc_id,type,status,enabled,name,format,size,metadata,index_status,path,parsed_path,process_config,source,error,gmt_create,gmt_modified,creator,modifier,tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
`

type CreateDocumentParams struct {
	WorkspaceID   string           `json:"workspace_id"`
	KbID          string           `json:"kb_id"`
	DocID         string           `json:"doc_id"`
	Type          string           `json:"type"`
	Status        int16            `json:"status"`
	Enabled       int16            `json:"enabled"`
	Name          string           `json:"name"`
	Format        string           `json:"format"`
	Size          int64            `json:"size"`
	Metadata      pgtype.Text      `json:"metadata"`
	IndexStatus   int16            `json:"index_status"`
	Path          string           `json:"path"`
	ParsedPath    pgtype.Text      `json:"parsed_path"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	Source        pgtype.Text      `json:"source"`
	Error         pgtype.Text      `json:"error"`
	GmtCreate     pgtype.Timestamp `json:"gmt_create"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Creator       string           `json:"creator"`
	Modifier      string           `json:"modifier"`
	TenantID      pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.WorkspaceID,
		arg.KbID,
		arg.DocID,
		arg.Type,
		arg.Status,
		arg.Enabled,
		arg.Name,
		arg.Format,
		arg.Size,
		arg.Metadata,
		arg.IndexStatus,
		arg.Path,
		arg.ParsedPath,
		arg.ProcessConfig,
		arg.Source,
		arg.Error,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const createDocumentChunk = `-- name: CreateDocumentChunk :exec
INSERT INTO document_chunk (workspace_id,kb_id,doc_id,chunk_id,doc_name,title,text,score,page_number,enabled,status,gmt_create,gmt_modified,creator,modifier,tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1,$11,$12,$13,$14,$15)
`

type CreateDocumentChunkParams struct {
	WorkspaceID string           `json:"workspace_id"`
	KbID        string           `json:"kb_id"`
	DocID       string           `json:"doc_id"`
	ChunkID     string           `json:"chunk_id"`
	DocName     string           `json:"doc_name"`
	Title       string           `json:"title"`
	Text        string           `json:"text"`
	Score       pgtype.Float8    `json:"score"`
	PageNumber  pgtype.Int4      `json:"page_number"`
	Enabled     int16            `json:"enabled"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateDocumentChunk(ctx context.Context, arg CreateDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, createDocumentChunk,
		arg.WorkspaceID,
		arg.KbID,
		arg.DocID,
		arg.ChunkID,
		arg.DocName,
		arg.Title,
		arg.Text,
		arg.Score,
		arg.PageNumber,
		arg.Enabled,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deleteDocument = `-- name: DeleteDocument :exec
UPDATE document SET status=0,gmt_modified=$4,modifier=$5 WHERE workspace_id=$1 AND kb_id=$2 AND doc_id=$3 AND status<>0
`

type DeleteDocumentParams struct {
	WorkspaceID string           `json:"workspace_id"`
	KbID        string           `json:"kb_id"`
	DocID       string           `json:"doc_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument,
		arg.WorkspaceID,
		arg.KbID,
		arg.DocID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
UPDATE document_chunk SET status=0,gmt_modified=$4,modifier=$5
WHERE workspace_id=$1 AND doc_id=$2 AND chunk_id=ANY($3::text[]) AND status<>0
`

type DeleteDocumentChunksParams struct {
	WorkspaceID string           `json:"workspace_id"`
	DocID       string           `json:"doc_id"`
	Column3     []string         `json:"column_3"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) DeleteDocumentChunks(ctx context.Context, arg DeleteDocumentChunksParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentChunks,
		arg.WorkspaceID,
		arg.DocID,
		arg.Column3,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const findActiveDocument = `-- name: FindActiveDocument :one
SELECT id,workspace_id,kb_id,doc_id,type,status,enabled,name,format,size,metadata,index_status,path,parsed_path,process_config,source,error,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM document WHERE workspace_id=$1 AND kb_id=$2 AND doc_id=$3 AND status<>0 LIMIT 1
`

type FindActiveDocumentParams struct {
	WorkspaceID string `json:"workspace_id"`
	KbID        string `json:"kb_id"`
	DocID       string `json:"doc_id"`
}

func (q *Queries) FindActiveDocument(ctx context.Context, arg FindActiveDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, findActiveDocument, arg.WorkspaceID, arg.KbID, arg.DocID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.DocID,
		&i.Type,
		&i.Status,
		&i.Enabled,
		&i.Name,
		&i.Format,
		&i.Size,
		&i.Metadata,
		&i.IndexStatus,
		&i.Path,
		&i.ParsedPath,
		&i.ProcessConfig,
		&i.Source,
		&i.Error,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveDocumentByDocID = `-- name: FindActiveDocumentByDocID :one
SELECT id,workspace_id,kb_id,doc_id,type,status,enabled,name,format,size,metadata,index_status,path,parsed_path,process_config,source,error,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM document WHERE workspace_id=$1 AND doc_id=$2 AND status<>0 LIMIT 1
`

type FindActiveDocumentByDocIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	DocID       string `json:"doc_id"`
}

func (q *Queries) FindActiveDocumentByDocID(ctx context.Context, arg FindActiveDocumentByDocIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, findActiveDocumentByDocID, arg.WorkspaceID, arg.DocID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.DocID,
		&i.Type,
		&i.Status,
		&i.Enabled,
		&i.Name,
		&i.Format,
		&i.Size,
		&i.Metadata,
		&i.IndexStatus,
		&i.Path,
		&i.ParsedPath,
		&i.ProcessConfig,
		&i.Source,
		&i.Error,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveDocumentChunk = `-- name: FindActiveDocumentChunk :one
SELECT id,workspace_id,kb_id,doc_id,chunk_id,doc_name,title,text,score,page_number,enabled,status,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM document_chunk WHERE workspace_id=$1 AND doc_id=$2 AND chunk_id=$3 AND status<>0 LIMIT 1
`

type FindActiveDocumentChunkParams struct {
	WorkspaceID string `json:"workspace_id"`
	DocID       string `json:"doc_id"`
	ChunkID     string `json:"chunk_id"`
}

func (q *Queries) FindActiveDocumentChunk(ctx context.Context, arg FindActiveDocumentChunkParams) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, findActiveDocumentChunk, arg.WorkspaceID, arg.DocID, arg.ChunkID)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.DocID,
		&i.ChunkID,
		&i.DocName,
		&i.Title,
		&i.Text,
		&i.Score,
		&i.PageNumber,
		&i.Enabled,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActiveDocumentChunks = `-- name: ListActiveDocumentChunks :many
SELECT id,workspace_id,kb_id,doc_id,chunk_id,doc_name,title,text,score,page_number,enabled,status,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM document_chunk WHERE workspace_id=$1 AND doc_id=$2 AND status<>0 ORDER BY gmt_modified DESC
`

type ListActiveDocumentChunksParams struct {
	WorkspaceID string `json:"workspace_id"`
	DocID       string `json:"doc_id"`
}

func (q *Queries) ListActiveDocumentChunks(ctx context.Context, arg ListActiveDocumentChunksParams) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listActiveDocumentChunks, arg.WorkspaceID, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KbID,
			&i.DocID,
			&i.ChunkID,
			&i.DocName,
			&i.Title,
			&i.Text,
			&i.Score,
			&i.PageNumber,
			&i.Enabled,
			&i.Status,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDocuments = `-- name: ListActiveDocuments :many
SELECT id,workspace_id,kb_id,doc_id,type,status,enabled,name,format,size,metadata,index_status,path,parsed_path,process_config,source,error,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM document WHERE workspace_id=$1 AND kb_id=$2 AND ($3::text='' OR name ILIKE '%' || $3::text || '%') AND ($4::smallint < 0 OR index_status=$4) AND status<>0 ORDER BY gmt_modified DESC
`

type ListActiveDocumentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	KbID        string `json:"kb_id"`
	Column3     string `json:"column_3"`
	Column4     int16  `json:"column_4"`
}

func (q *Queries) ListActiveDocuments(ctx context.Context, arg ListActiveDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listActiveDocuments,
		arg.WorkspaceID,
		arg.KbID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KbID,
			&i.DocID,
			&i.Type,
			&i.Status,
			&i.Enabled,
			&i.Name,
			&i.Format,
			&i.Size,
			&i.Metadata,
			&i.IndexStatus,
			&i.Path,
			&i.ParsedPath,
			&i.ProcessConfig,
			&i.Source,
			&i.Error,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE document SET enabled=$4,name=$5,format=$6,size=$7,metadata=$8,index_status=$9,path=$10,parsed_path=$11,process_config=$12,source=$13,error=$14,gmt_modified=$15,modifier=$16
WHERE workspace_id=$1 AND kb_id=$2 AND doc_id=$3 AND status<>0
`

type UpdateDocumentParams struct {
	WorkspaceID   string           `json:"workspace_id"`
	KbID          string           `json:"kb_id"`
	DocID         string           `json:"doc_id"`
	Enabled       int16            `json:"enabled"`
	Name          string           `json:"name"`
	Format        string           `json:"format"`
	Size          int64            `json:"size"`
	Metadata      pgtype.Text      `json:"metadata"`
	IndexStatus   int16            `json:"index_status"`
	Path          string           `json:"path"`
	ParsedPath    pgtype.Text      `json:"parsed_path"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	Source        pgtype.Text      `json:"source"`
	Error         pgtype.Text      `json:"error"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Modifier      string           `json:"modifier"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.Exec(ctx, updateDocument,
		arg.WorkspaceID,
		arg.KbID,
		arg.DocID,
		arg.Enabled,
		arg.Name,
		arg.Format,
		arg.Size,
		arg.Metadata,
		arg.IndexStatus,
		arg.Path,
		arg.ParsedPath,
		arg.ProcessConfig,
		arg.Source,
		arg.Error,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateDocumentChunk = `-- name: UpdateDocumentChunk :exec
UPDATE document_chunk SET title=$4,text=$5,score=$6,page_number=$7,enabled=$8,gmt_modified=$9,modifier=$10
WHERE workspace_id=$1 AND doc_id=$2 AND chunk_id=$3 AND status<>0
`

type UpdateDocumentChunkParams struct {
	WorkspaceID string           `json:"workspace_id"`
	DocID       string           `json:"doc_id"`
	ChunkID     string           `json:"chunk_id"`
	Title       string           `json:"title"`
	Text        string           `json:"text"`
	Score       pgtype.Float8    `json:"score"`
	PageNumber  pgtype.Int4      `json:"page_number"`
	Enabled     int16            `json:"enabled"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateDocumentChunk(ctx context.Context, arg UpdateDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, updateDocumentChunk,
		arg.WorkspaceID,
		arg.DocID,
		arg.ChunkID,
		arg.Title,
		arg.Text,
		arg.Score,
		arg.PageNumber,
		arg.Enabled,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateDocumentChunksEnabled = `-- name: UpdateDocumentChunksEnabled :exec
UPDATE document_chunk SET enabled=$4,gmt_modified=$5,modifier=$6
WHERE workspace_id=$1 AND doc_id=$2 AND chunk_id=ANY($3::text[]) AND status<>0
`

type UpdateDocumentChunksEnabledParams struct {
	WorkspaceID string           `json:"workspace_id"`
	DocID       string           `json:"doc_id"`
	Column3     []string         `json:"column_3"`
	Enabled     int16            `json:"enabled"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateDocumentChunksEnabled(ctx context.Context, arg UpdateDocumentChunksEnabledParams) error {
	_, err := q.db.Exec(ctx, updateDocumentChunksEnabled,
		arg.WorkspaceID,
		arg.DocID,
		arg.Column3,
		arg.Enabled,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
