// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_base.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKnowledgeBase = `-- name: CreateKnowledgeBase :exec
INSERT INTO knowledge_base (workspace_id, kb_id, type, status, name, description, process_config, index_config, search_config, total_docs, gmt_create, gmt_modified, creator, modifier, tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreateKnowledgeBaseParams struct {
	WorkspaceID   string           `json:"workspace_id"`
	KbID          string           `json:"kb_id"`
	Type          string           `json:"type"`
	Status        int16            `json:"status"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	IndexConfig   pgtype.Text      `json:"index_config"`
	SearchConfig  pgtype.Text      `json:"search_config"`
	TotalDocs     int64            `json:"total_docs"`
	GmtCreate     pgtype.Timestamp `json:"gmt_create"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Creator       string           `json:"creator"`
	Modifier      string           `json:"modifier"`
	TenantID      pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, createKnowledgeBase,
		arg.WorkspaceID,
		arg.KbID,
		arg.Type,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.ProcessConfig,
		arg.IndexConfig,
		arg.SearchConfig,
		arg.TotalDocs,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deleteKnowledgeBase = `-- name: DeleteKnowledgeBase :exec
UPDATE knowledge_base SET status=0,gmt_modified=$3,modifier=$4 WHERE kb_id=$1 AND workspace_id=$2 AND status<>0
`

type DeleteKnowledgeBaseParams struct {
	KbID        string           `json:"kb_id"`
	WorkspaceID string           `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) DeleteKnowledgeBase(ctx context.Context, arg DeleteKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeBase,
		arg.KbID,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const findActiveKnowledgeBase = `-- name: FindActiveKnowledgeBase :one
SELECT id, workspace_id, kb_id, type, status, name, description, process_config, index_config, search_config, total_docs, gmt_create, gmt_modified, creator, modifier, tenant_id FROM knowledge_base WHERE kb_id=$1 AND workspace_id=$2 AND status<>0 LIMIT 1
`

type FindActiveKnowledgeBaseParams struct {
	KbID        string `json:"kb_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindActiveKnowledgeBase(ctx context.Context, arg FindActiveKnowledgeBaseParams) (KnowledgeBase, error) {
	row := q.db.QueryRow(ctx, findActiveKnowledgeBase, arg.KbID, arg.WorkspaceID)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.Type,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.ProcessConfig,
		&i.IndexConfig,
		&i.SearchConfig,
		&i.TotalDocs,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActiveKnowledgeBases = `-- name: ListActiveKnowledgeBases :many
SELECT id, workspace_id, kb_id, type, status, name, description, process_config, index_config, search_config, total_docs, gmt_create, gmt_modified, creator, modifier, tenant_id FROM knowledge_base WHERE workspace_id=$1 AND ($2::text='' OR name ILIKE '%' || $2::text || '%') AND status<>0 ORDER BY gmt_modified DESC
`

type ListActiveKnowledgeBasesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
}

func (q *Queries) ListActiveKnowledgeBases(ctx context.Context, arg ListActiveKnowledgeBasesParams) ([]KnowledgeBase, error) {
	rows, err := q.db.Query(ctx, listActiveKnowledgeBases, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeBase
	for rows.Next() {
		var i KnowledgeBase
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KbID,
			&i.Type,
			&i.Status,
			&i.Name,
			&i.Description,
			&i.ProcessConfig,
			&i.IndexConfig,
			&i.SearchConfig,
			&i.TotalDocs,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :exec
UPDATE knowledge_base SET type=$3,name=$4,description=$5,process_config=$6,index_config=$7,search_config=$8,gmt_modified=$9,modifier=$10 WHERE kb_id=$1 AND workspace_id=$2 AND status<>0
`

type UpdateKnowledgeBaseParams struct {
	KbID          string           `json:"kb_id"`
	WorkspaceID   string           `json:"workspace_id"`
	Type          string           `json:"type"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	IndexConfig   pgtype.Text      `json:"index_config"`
	SearchConfig  pgtype.Text      `json:"search_config"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Modifier      string           `json:"modifier"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, updateKnowledgeBase,
		arg.KbID,
		arg.WorkspaceID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.ProcessConfig,
		arg.IndexConfig,
		arg.SearchConfig,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
