// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_server.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMcpServer = `-- name: CreateMcpServer :exec
INSERT INTO mcp_server (gmt_create,gmt_modified,server_code,name,description,source,type,deploy_config,workspace_id,account_id,status,detail_config,install_type,tenant_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type CreateMcpServerParams struct {
	GmtCreate    pgtype.Timestamp `json:"gmt_create"`
	GmtModified  pgtype.Timestamp `json:"gmt_modified"`
	ServerCode   string           `json:"server_code"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Source       pgtype.Text      `json:"source"`
	Type         string           `json:"type"`
	DeployConfig string           `json:"deploy_config"`
	WorkspaceID  pgtype.Text      `json:"workspace_id"`
	AccountID    pgtype.Text      `json:"account_id"`
	Status       int16            `json:"status"`
	DetailConfig pgtype.Text      `json:"detail_config"`
	InstallType  pgtype.Text      `json:"install_type"`
	TenantID     pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateMcpServer(ctx context.Context, arg CreateMcpServerParams) error {
	_, err := q.db.Exec(ctx, createMcpServer,
		arg.GmtCreate,
		arg.GmtModified,
		arg.ServerCode,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Type,
		arg.DeployConfig,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Status,
		arg.DetailConfig,
		arg.InstallType,
		arg.TenantID,
	)
	return err
}

const deleteMcpServer = `-- name: DeleteMcpServer :exec
UPDATE mcp_server SET status=3,gmt_modified=$3 WHERE server_code=$1 AND workspace_id=$2 AND status<>3
`

type DeleteMcpServerParams struct {
	ServerCode  string           `json:"server_code"`
	WorkspaceID pgtype.Text      `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
}

func (q *Queries) DeleteMcpServer(ctx context.Context, arg DeleteMcpServerParams) error {
	_, err := q.db.Exec(ctx, deleteMcpServer, arg.ServerCode, arg.WorkspaceID, arg.GmtModified)
	return err
}

const findActiveMcpServer = `-- name: FindActiveMcpServer :one
SELECT id,gmt_create,gmt_modified,server_code,name,description,source,deploy_env,type,deploy_config,workspace_id,account_id,status,biz_type,detail_config,host,install_type,tenant_id FROM mcp_server WHERE server_code=$1 AND workspace_id=$2 AND status<>3 LIMIT 1
`

type FindActiveMcpServerParams struct {
	ServerCode  string      `json:"server_code"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) FindActiveMcpServer(ctx context.Context, arg FindActiveMcpServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, findActiveMcpServer, arg.ServerCode, arg.WorkspaceID)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.ServerCode,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.DeployEnv,
		&i.Type,
		&i.DeployConfig,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Status,
		&i.BizType,
		&i.DetailConfig,
		&i.Host,
		&i.InstallType,
		&i.TenantID,
	)
	return i, err
}

const listActiveMcpServers = `-- name: ListActiveMcpServers :many
SELECT id,gmt_create,gmt_modified,server_code,name,description,source,deploy_env,type,deploy_config,workspace_id,account_id,status,biz_type,detail_config,host,install_type,tenant_id FROM mcp_server WHERE workspace_id=$1 AND ($2::text='' OR name ILIKE '%' || $2::text || '%') AND status<>3 ORDER BY gmt_modified DESC
`

type ListActiveMcpServersParams struct {
	WorkspaceID pgtype.Text `json:"workspace_id"`
	Column2     string      `json:"column_2"`
}

func (q *Queries) ListActiveMcpServers(ctx context.Context, arg ListActiveMcpServersParams) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listActiveMcpServers, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.ServerCode,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.DeployEnv,
			&i.Type,
			&i.DeployConfig,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Status,
			&i.BizType,
			&i.DetailConfig,
			&i.Host,
			&i.InstallType,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMcpServer = `-- name: UpdateMcpServer :exec
UPDATE mcp_server SET gmt_modified=$3,name=$4,description=$5,source=$6,type=$7,deploy_config=$8,status=$9,detail_config=$10,install_type=$11 WHERE server_code=$1 AND workspace_id=$2 AND status<>3
`

type UpdateMcpServerParams struct {
	ServerCode   string           `json:"server_code"`
	WorkspaceID  pgtype.Text      `json:"workspace_id"`
	GmtModified  pgtype.Timestamp `json:"gmt_modified"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Source       pgtype.Text      `json:"source"`
	Type         string           `json:"type"`
	DeployConfig string           `json:"deploy_config"`
	Status       int16            `json:"status"`
	DetailConfig pgtype.Text      `json:"detail_config"`
	InstallType  pgtype.Text      `json:"install_type"`
}

func (q *Queries) UpdateMcpServer(ctx context.Context, arg UpdateMcpServerParams) error {
	_, err := q.db.Exec(ctx, updateMcpServer,
		arg.ServerCode,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Type,
		arg.DeployConfig,
		arg.Status,
		arg.DetailConfig,
		arg.InstallType,
	)
	return err
}
