// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModel = `-- name: CreateModel :exec
INSERT INTO model (
    workspace_id, icon, name, type, mode, model_id, provider, enable, tags, source,
    gmt_create, gmt_modified, creator, modifier, tenant_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateModelParams struct {
	WorkspaceID pgtype.Text      `json:"workspace_id"`
	Icon        pgtype.Text      `json:"icon"`
	Name        pgtype.Text      `json:"name"`
	Type        pgtype.Text      `json:"type"`
	Mode        pgtype.Text      `json:"mode"`
	ModelID     string           `json:"model_id"`
	Provider    string           `json:"provider"`
	Enable      pgtype.Int2      `json:"enable"`
	Tags        pgtype.Text      `json:"tags"`
	Source      string           `json:"source"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.Exec(ctx, createModel,
		arg.WorkspaceID,
		arg.Icon,
		arg.Name,
		arg.Type,
		arg.Mode,
		arg.ModelID,
		arg.Provider,
		arg.Enable,
		arg.Tags,
		arg.Source,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM model
WHERE provider = $1 AND model_id = $2 AND workspace_id = $3
`

type DeleteModelParams struct {
	Provider    string      `json:"provider"`
	ModelID     string      `json:"model_id"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) DeleteModel(ctx context.Context, arg DeleteModelParams) error {
	_, err := q.db.Exec(ctx, deleteModel, arg.Provider, arg.ModelID, arg.WorkspaceID)
	return err
}

const findModelByProviderAndIDAndWorkspace = `-- name: FindModelByProviderAndIDAndWorkspace :one
SELECT id, workspace_id, icon, name, type, mode, model_id, provider, enable, tags, source,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM model
WHERE provider = $1 AND model_id = $2 AND workspace_id = $3
LIMIT 1
`

type FindModelByProviderAndIDAndWorkspaceParams struct {
	Provider    string      `json:"provider"`
	ModelID     string      `json:"model_id"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) FindModelByProviderAndIDAndWorkspace(ctx context.Context, arg FindModelByProviderAndIDAndWorkspaceParams) (Model, error) {
	row := q.db.QueryRow(ctx, findModelByProviderAndIDAndWorkspace, arg.Provider, arg.ModelID, arg.WorkspaceID)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Icon,
		&i.Name,
		&i.Type,
		&i.Mode,
		&i.ModelID,
		&i.Provider,
		&i.Enable,
		&i.Tags,
		&i.Source,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listModelsByProviderAndWorkspace = `-- name: ListModelsByProviderAndWorkspace :many
SELECT id, workspace_id, icon, name, type, mode, model_id, provider, enable, tags, source,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM model
WHERE provider = $1 AND workspace_id = $2
ORDER BY id ASC
`

type ListModelsByProviderAndWorkspaceParams struct {
	Provider    string      `json:"provider"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) ListModelsByProviderAndWorkspace(ctx context.Context, arg ListModelsByProviderAndWorkspaceParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModelsByProviderAndWorkspace, arg.Provider, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Icon,
			&i.Name,
			&i.Type,
			&i.Mode,
			&i.ModelID,
			&i.Provider,
			&i.Enable,
			&i.Tags,
			&i.Source,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByWorkspace = `-- name: ListModelsByWorkspace :many
SELECT id, workspace_id, icon, name, type, mode, model_id, provider, enable, tags, source,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM model
WHERE workspace_id = $1
ORDER BY id ASC
`

func (q *Queries) ListModelsByWorkspace(ctx context.Context, workspaceID pgtype.Text) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModelsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Icon,
			&i.Name,
			&i.Type,
			&i.Mode,
			&i.ModelID,
			&i.Provider,
			&i.Enable,
			&i.Tags,
			&i.Source,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :exec
UPDATE model
SET icon = $4,
    name = $5,
    enable = $6,
    tags = $7,
    gmt_modified = $8,
    modifier = $9
WHERE provider = $1 AND model_id = $2 AND workspace_id = $3
`

type UpdateModelParams struct {
	Provider    string           `json:"provider"`
	ModelID     string           `json:"model_id"`
	WorkspaceID pgtype.Text      `json:"workspace_id"`
	Icon        pgtype.Text      `json:"icon"`
	Name        pgtype.Text      `json:"name"`
	Enable      pgtype.Int2      `json:"enable"`
	Tags        pgtype.Text      `json:"tags"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.Exec(ctx, updateModel,
		arg.Provider,
		arg.ModelID,
		arg.WorkspaceID,
		arg.Icon,
		arg.Name,
		arg.Enable,
		arg.Tags,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
