// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int64            `json:"id"`
	AccountID    string           `json:"account_id"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	Mobile       pgtype.Text      `json:"mobile"`
	Password     string           `json:"password"`
	Nickname     pgtype.Text      `json:"nickname"`
	Icon         pgtype.Text      `json:"icon"`
	Type         string           `json:"type"`
	Status       int16            `json:"status"`
	GmtCreate    pgtype.Timestamp `json:"gmt_create"`
	GmtModified  pgtype.Timestamp `json:"gmt_modified"`
	GmtLastLogin pgtype.Timestamp `json:"gmt_last_login"`
	Creator      string           `json:"creator"`
	Modifier     string           `json:"modifier"`
	TenantID     pgtype.Int8      `json:"tenant_id"`
}

type AgentSchema struct {
	ID          int64            `json:"id"`
	AgentID     pgtype.Text      `json:"agent_id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Type        string           `json:"type"`
	Instruction pgtype.Text      `json:"instruction"`
	InputKeys   pgtype.Text      `json:"input_keys"`
	OutputKey   pgtype.Text      `json:"output_key"`
	Handle      pgtype.Text      `json:"handle"`
	SubAgents   pgtype.Text      `json:"sub_agents"`
	YamlSchema  pgtype.Text      `json:"yaml_schema"`
	Status      string           `json:"status"`
	Enabled     int16            `json:"enabled"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type ApiKey struct {
	ID           int64            `json:"id"`
	AccountID    string           `json:"account_id"`
	ApiKey       string           `json:"api_key"`
	Status       int16            `json:"status"`
	Description  pgtype.Text      `json:"description"`
	GmtCreate    pgtype.Timestamp `json:"gmt_create"`
	GmtModified  pgtype.Timestamp `json:"gmt_modified"`
	Creator      string           `json:"creator"`
	Modifier     string           `json:"modifier"`
	TenantID     pgtype.Int8      `json:"tenant_id"`
	ApiKeyHash   pgtype.Text      `json:"api_key_hash"`
	ApiKeyPrefix pgtype.Text      `json:"api_key_prefix"`
}

type Application struct {
	ID          int64            `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	AppID       string           `json:"app_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Icon        pgtype.Text      `json:"icon"`
	Source      string           `json:"source"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type ApplicationComponent struct {
	ID          int64            `json:"id"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Code        string           `json:"code"`
	Name        string           `json:"name"`
	WorkspaceID string           `json:"workspace_id"`
	Type        string           `json:"type"`
	AppID       pgtype.Text      `json:"app_id"`
	Config      pgtype.Text      `json:"config"`
	Description pgtype.Text      `json:"description"`
	Status      pgtype.Int2      `json:"status"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
	NeedUpdate  pgtype.Int2      `json:"need_update"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type ApplicationVersion struct {
	ID          int64            `json:"id"`
	AppID       string           `json:"app_id"`
	WorkspaceID string           `json:"workspace_id"`
	Config      pgtype.Text      `json:"config"`
	Status      int16            `json:"status"`
	Version     string           `json:"version"`
	Description pgtype.Text      `json:"description"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type AuthTokenSession struct {
	ID          int64            `json:"id"`
	TokenID     string           `json:"token_id"`
	AccountID   string           `json:"account_id"`
	TokenType   string           `json:"token_type"`
	TokenHash   string           `json:"token_hash"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	Revoked     int16            `json:"revoked"`
	Source      pgtype.Text      `json:"source"`
	CallerIp    pgtype.Text      `json:"caller_ip"`
	UserAgent   pgtype.Text      `json:"user_agent"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type Dataset struct {
	ID            int64            `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	ColumnsConfig pgtype.Text      `json:"columns_config"`
	DataCount     int32            `json:"data_count"`
	CreateTime    pgtype.Timestamp `json:"create_time"`
	UpdateTime    pgtype.Timestamp `json:"update_time"`
	Deleted       int16            `json:"deleted"`
}

type DatasetItem struct {
	ID            int64            `json:"id"`
	DatasetID     int64            `json:"dataset_id"`
	ColumnsConfig pgtype.Text      `json:"columns_config"`
	DataContent   pgtype.Text      `json:"data_content"`
	Remark        pgtype.Text      `json:"remark"`
	CreateTime    pgtype.Timestamp `json:"create_time"`
	UpdateTime    pgtype.Timestamp `json:"update_time"`
	Deleted       int16            `json:"deleted"`
}

type DatasetVersion struct {
	ID            int64            `json:"id"`
	DatasetID     int64            `json:"dataset_id"`
	Version       string           `json:"version"`
	Description   pgtype.Text      `json:"description"`
	DataCount     int32            `json:"data_count"`
	Status        string           `json:"status"`
	Experiments   pgtype.Text      `json:"experiments"`
	DatasetItems  pgtype.Text      `json:"dataset_items"`
	ColumnsConfig pgtype.Text      `json:"columns_config"`
	CreateTime    pgtype.Timestamp `json:"create_time"`
	UpdateTime    pgtype.Timestamp `json:"update_time"`
}

type Document struct {
	ID            int64            `json:"id"`
	WorkspaceID   string           `json:"workspace_id"`
	KbID          string           `json:"kb_id"`
	DocID         string           `json:"doc_id"`
	Type          string           `json:"type"`
	Status        int16            `json:"status"`
	Enabled       int16            `json:"enabled"`
	Name          string           `json:"name"`
	Format        string           `json:"format"`
	Size          int64            `json:"size"`
	Metadata      pgtype.Text      `json:"metadata"`
	IndexStatus   int16            `json:"index_status"`
	Path          string           `json:"path"`
	ParsedPath    pgtype.Text      `json:"parsed_path"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	Source        pgtype.Text      `json:"source"`
	Error         pgtype.Text      `json:"error"`
	GmtCreate     pgtype.Timestamp `json:"gmt_create"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Creator       string           `json:"creator"`
	Modifier      string           `json:"modifier"`
	TenantID      pgtype.Int8      `json:"tenant_id"`
}

type DocumentChunk struct {
	ID          int64            `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	KbID        string           `json:"kb_id"`
	DocID       string           `json:"doc_id"`
	ChunkID     string           `json:"chunk_id"`
	DocName     string           `json:"doc_name"`
	Title       string           `json:"title"`
	Text        string           `json:"text"`
	Score       pgtype.Float8    `json:"score"`
	PageNumber  pgtype.Int4      `json:"page_number"`
	Enabled     int16            `json:"enabled"`
	Status      int16            `json:"status"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type Evaluator struct {
	ID            int64            `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	LatestVersion pgtype.Text      `json:"latest_version"`
	ModelName     pgtype.Text      `json:"model_name"`
	Prompt        pgtype.Text      `json:"prompt"`
	ModelConfig   pgtype.Text      `json:"model_config"`
	Variables     pgtype.Text      `json:"variables"`
	CreateTime    pgtype.Timestamp `json:"create_time"`
	UpdateTime    pgtype.Timestamp `json:"update_time"`
	Deleted       int16            `json:"deleted"`
}

type EvaluatorTemplate struct {
	ID                   int64            `json:"id"`
	EvaluatorTemplateKey string           `json:"evaluator_template_key"`
	TemplateDesc         pgtype.Text      `json:"template_desc"`
	Template             pgtype.Text      `json:"template"`
	Variables            pgtype.Text      `json:"variables"`
	ModelConfig          pgtype.Text      `json:"model_config"`
	CreateTime           pgtype.Timestamp `json:"create_time"`
	UpdateTime           pgtype.Timestamp `json:"update_time"`
}

type EvaluatorVersion struct {
	ID          int64            `json:"id"`
	EvaluatorID int64            `json:"evaluator_id"`
	Description pgtype.Text      `json:"description"`
	Version     string           `json:"version"`
	ModelConfig pgtype.Text      `json:"model_config"`
	Prompt      pgtype.Text      `json:"prompt"`
	Variables   pgtype.Text      `json:"variables"`
	Status      pgtype.Text      `json:"status"`
	Experiments pgtype.Text      `json:"experiments"`
	CreateTime  pgtype.Timestamp `json:"create_time"`
	UpdateTime  pgtype.Timestamp `json:"update_time"`
}

type Experiment struct {
	ID                     int64            `json:"id"`
	Name                   string           `json:"name"`
	Description            pgtype.Text      `json:"description"`
	DatasetID              pgtype.Int8      `json:"dataset_id"`
	DatasetVersionID       pgtype.Int8      `json:"dataset_version_id"`
	DatasetVersion         pgtype.Text      `json:"dataset_version"`
	EvaluationObjectConfig pgtype.Text      `json:"evaluation_object_config"`
	EvaluatorConfig        pgtype.Text      `json:"evaluator_config"`
	EvaluatorID            pgtype.Text      `json:"evaluator_id"`
	Status                 string           `json:"status"`
	Progress               int32            `json:"progress"`
	CompleteTime           pgtype.Timestamp `json:"complete_time"`
	CreateTime             pgtype.Timestamp `json:"create_time"`
	UpdateTime             pgtype.Timestamp `json:"update_time"`
}

type ExperimentResult struct {
	ID                 int64            `json:"id"`
	ExperimentID       int64            `json:"experiment_id"`
	Input              pgtype.Text      `json:"input"`
	ActualOutput       pgtype.Text      `json:"actual_output"`
	ReferenceOutput    pgtype.Text      `json:"reference_output"`
	Score              pgtype.Numeric   `json:"score"`
	Reason             pgtype.Text      `json:"reason"`
	EvaluationTime     pgtype.Timestamp `json:"evaluation_time"`
	EvaluatorVersionID pgtype.Int8      `json:"evaluator_version_id"`
	CreateTime         pgtype.Timestamp `json:"create_time"`
	UpdateTime         pgtype.Timestamp `json:"update_time"`
}

type KnowledgeBase struct {
	ID            int64            `json:"id"`
	WorkspaceID   string           `json:"workspace_id"`
	KbID          string           `json:"kb_id"`
	Type          string           `json:"type"`
	Status        int16            `json:"status"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	ProcessConfig pgtype.Text      `json:"process_config"`
	IndexConfig   pgtype.Text      `json:"index_config"`
	SearchConfig  pgtype.Text      `json:"search_config"`
	TotalDocs     int64            `json:"total_docs"`
	GmtCreate     pgtype.Timestamp `json:"gmt_create"`
	GmtModified   pgtype.Timestamp `json:"gmt_modified"`
	Creator       string           `json:"creator"`
	Modifier      string           `json:"modifier"`
	TenantID      pgtype.Int8      `json:"tenant_id"`
}

type McpServer struct {
	ID           int64            `json:"id"`
	GmtCreate    pgtype.Timestamp `json:"gmt_create"`
	GmtModified  pgtype.Timestamp `json:"gmt_modified"`
	ServerCode   string           `json:"server_code"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Source       pgtype.Text      `json:"source"`
	DeployEnv    pgtype.Text      `json:"deploy_env"`
	Type         string           `json:"type"`
	DeployConfig string           `json:"deploy_config"`
	WorkspaceID  pgtype.Text      `json:"workspace_id"`
	AccountID    pgtype.Text      `json:"account_id"`
	Status       int16            `json:"status"`
	BizType      pgtype.Text      `json:"biz_type"`
	DetailConfig pgtype.Text      `json:"detail_config"`
	Host         pgtype.Text      `json:"host"`
	InstallType  pgtype.Text      `json:"install_type"`
	TenantID     pgtype.Int8      `json:"tenant_id"`
}

type Model struct {
	ID          int64            `json:"id"`
	WorkspaceID pgtype.Text      `json:"workspace_id"`
	Icon        pgtype.Text      `json:"icon"`
	Name        pgtype.Text      `json:"name"`
	Type        pgtype.Text      `json:"type"`
	Mode        pgtype.Text      `json:"mode"`
	ModelID     string           `json:"model_id"`
	Provider    string           `json:"provider"`
	Enable      pgtype.Int2      `json:"enable"`
	Tags        pgtype.Text      `json:"tags"`
	Source      string           `json:"source"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type ModelConfig struct {
	ID                  int64            `json:"id"`
	Name                string           `json:"name"`
	Provider            string           `json:"provider"`
	ModelName           string           `json:"model_name"`
	BaseUrl             string           `json:"base_url"`
	ApiKey              string           `json:"api_key"`
	DefaultParameters   []byte           `json:"default_parameters"`
	SupportedParameters []byte           `json:"supported_parameters"`
	Status              int16            `json:"status"`
	CreateTime          pgtype.Timestamp `json:"create_time"`
	UpdateTime          pgtype.Timestamp `json:"update_time"`
	Deleted             int16            `json:"deleted"`
}

type Plugin struct {
	ID          int64            `json:"id"`
	PluginID    string           `json:"plugin_id"`
	WorkspaceID string           `json:"workspace_id"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      pgtype.Text      `json:"config"`
	Source      string           `json:"source"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type Prompt struct {
	ID                  int64            `json:"id"`
	PromptKey           string           `json:"prompt_key"`
	PromptDesc          pgtype.Text      `json:"prompt_desc"`
	PromptDescription   pgtype.Text      `json:"prompt_description"`
	LatestVersion       pgtype.Text      `json:"latest_version"`
	LatestVersionStatus pgtype.Text      `json:"latest_version_status"`
	Tags                pgtype.Text      `json:"tags"`
	CreateTime          pgtype.Timestamp `json:"create_time"`
	UpdateTime          pgtype.Timestamp `json:"update_time"`
}

type PromptBuildTemplate struct {
	ID                int64            `json:"id"`
	PromptTemplateKey string           `json:"prompt_template_key"`
	Tags              pgtype.Text      `json:"tags"`
	TemplateDesc      pgtype.Text      `json:"template_desc"`
	Template          pgtype.Text      `json:"template"`
	Variables         pgtype.Text      `json:"variables"`
	ModelConfig       pgtype.Text      `json:"model_config"`
	CreateTime        pgtype.Timestamp `json:"create_time"`
	UpdateTime        pgtype.Timestamp `json:"update_time"`
}

type PromptVersion struct {
	ID                 int64            `json:"id"`
	Version            string           `json:"version"`
	PromptKey          string           `json:"prompt_key"`
	VersionDesc        pgtype.Text      `json:"version_desc"`
	VersionDescription pgtype.Text      `json:"version_description"`
	Template           pgtype.Text      `json:"template"`
	Variables          pgtype.Text      `json:"variables"`
	ModelConfig        pgtype.Text      `json:"model_config"`
	Status             string           `json:"status"`
	CreateTime         pgtype.Timestamp `json:"create_time"`
	UpdateTime         pgtype.Timestamp `json:"update_time"`
	PreviousVersion    pgtype.Text      `json:"previous_version"`
}

type Provider struct {
	ID                  int64            `json:"id"`
	WorkspaceID         pgtype.Text      `json:"workspace_id"`
	Icon                pgtype.Text      `json:"icon"`
	Name                pgtype.Text      `json:"name"`
	Description         pgtype.Text      `json:"description"`
	Provider            string           `json:"provider"`
	Enable              pgtype.Int2      `json:"enable"`
	Source              string           `json:"source"`
	Credential          pgtype.Text      `json:"credential"`
	SupportedModelTypes pgtype.Text      `json:"supported_model_types"`
	Protocol            pgtype.Text      `json:"protocol"`
	GmtCreate           pgtype.Timestamp `json:"gmt_create"`
	GmtModified         pgtype.Timestamp `json:"gmt_modified"`
	Creator             pgtype.Text      `json:"creator"`
	Modifier            pgtype.Text      `json:"modifier"`
	TenantID            pgtype.Int8      `json:"tenant_id"`
}

type Reference struct {
	ID          int64            `json:"id"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	MainCode    string           `json:"main_code"`
	MainType    int16            `json:"main_type"`
	ReferCode   string           `json:"refer_code"`
	ReferType   int16            `json:"refer_type"`
	WorkspaceID string           `json:"workspace_id"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type Skill struct {
	ID          int64            `json:"id"`
	SkillCode   string           `json:"skill_code"`
	WorkspaceID string           `json:"workspace_id"`
	AccountID   pgtype.Text      `json:"account_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Source      string           `json:"source"`
	Status      int16            `json:"status"`
	Tags        pgtype.Text      `json:"tags"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type SkillVersion struct {
	ID               int64            `json:"id"`
	SkillCode        string           `json:"skill_code"`
	WorkspaceID      string           `json:"workspace_id"`
	Version          string           `json:"version"`
	Description      pgtype.Text      `json:"description"`
	MainFilePath     string           `json:"main_file_path"`
	Manifest         pgtype.Text      `json:"manifest"`
	ContentHash      pgtype.Text      `json:"content_hash"`
	StorageType      string           `json:"storage_type"`
	StorageBucket    pgtype.Text      `json:"storage_bucket"`
	StoragePrefix    string           `json:"storage_prefix"`
	PackageObjectKey pgtype.Text      `json:"package_object_key"`
	FileCount        pgtype.Int4      `json:"file_count"`
	TotalSizeBytes   pgtype.Int8      `json:"total_size_bytes"`
	Status           int16            `json:"status"`
	GmtCreate        pgtype.Timestamp `json:"gmt_create"`
	GmtModified      pgtype.Timestamp `json:"gmt_modified"`
	Creator          pgtype.Text      `json:"creator"`
	Modifier         pgtype.Text      `json:"modifier"`
	TenantID         pgtype.Int8      `json:"tenant_id"`
}

type Tool struct {
	ID          int64            `json:"id"`
	PluginID    string           `json:"plugin_id"`
	ToolID      string           `json:"tool_id"`
	WorkspaceID string           `json:"workspace_id"`
	Status      int16            `json:"status"`
	Enabled     int16            `json:"enabled"`
	TestStatus  int16            `json:"test_status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      string           `json:"config"`
	ApiSchema   string           `json:"api_schema"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

type Workspace struct {
	ID          int64            `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	AccountID   string           `json:"account_id"`
	Status      int16            `json:"status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      pgtype.Text      `json:"config"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}
