// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlugin = `-- name: CreatePlugin :exec
INSERT INTO plugin (plugin_id,workspace_id,type,status,name,description,config,source,gmt_create,gmt_modified,creator,modifier,tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type CreatePluginParams struct {
	PluginID    string           `json:"plugin_id"`
	WorkspaceID string           `json:"workspace_id"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      pgtype.Text      `json:"config"`
	Source      string           `json:"source"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) error {
	_, err := q.db.Exec(ctx, createPlugin,
		arg.PluginID,
		arg.WorkspaceID,
		arg.Type,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Source,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const createPluginTool = `-- name: CreatePluginTool :exec
INSERT INTO tool (plugin_id,tool_id,workspace_id,status,enabled,test_status,name,description,config,api_schema,gmt_create,gmt_modified,creator,modifier,tenant_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreatePluginToolParams struct {
	PluginID    string           `json:"plugin_id"`
	ToolID      string           `json:"tool_id"`
	WorkspaceID string           `json:"workspace_id"`
	Status      int16            `json:"status"`
	Enabled     int16            `json:"enabled"`
	TestStatus  int16            `json:"test_status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      string           `json:"config"`
	ApiSchema   string           `json:"api_schema"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreatePluginTool(ctx context.Context, arg CreatePluginToolParams) error {
	_, err := q.db.Exec(ctx, createPluginTool,
		arg.PluginID,
		arg.ToolID,
		arg.WorkspaceID,
		arg.Status,
		arg.Enabled,
		arg.TestStatus,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ApiSchema,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM plugin WHERE plugin_id=$1 AND workspace_id=$2
`

type DeletePluginParams struct {
	PluginID    string `json:"plugin_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeletePlugin(ctx context.Context, arg DeletePluginParams) error {
	_, err := q.db.Exec(ctx, deletePlugin, arg.PluginID, arg.WorkspaceID)
	return err
}

const deletePluginTool = `-- name: DeletePluginTool :exec
DELETE FROM tool WHERE plugin_id=$1 AND tool_id=$2 AND workspace_id=$3
`

type DeletePluginToolParams struct {
	PluginID    string `json:"plugin_id"`
	ToolID      string `json:"tool_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeletePluginTool(ctx context.Context, arg DeletePluginToolParams) error {
	_, err := q.db.Exec(ctx, deletePluginTool, arg.PluginID, arg.ToolID, arg.WorkspaceID)
	return err
}

const deletePluginTools = `-- name: DeletePluginTools :exec
DELETE FROM tool WHERE plugin_id=$1 AND workspace_id=$2
`

type DeletePluginToolsParams struct {
	PluginID    string `json:"plugin_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeletePluginTools(ctx context.Context, arg DeletePluginToolsParams) error {
	_, err := q.db.Exec(ctx, deletePluginTools, arg.PluginID, arg.WorkspaceID)
	return err
}

const findActivePlugin = `-- name: FindActivePlugin :one
SELECT id,plugin_id,workspace_id,type,status,name,description,config,source,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM plugin WHERE plugin_id=$1 AND workspace_id=$2 AND status<>0 LIMIT 1
`

type FindActivePluginParams struct {
	PluginID    string `json:"plugin_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindActivePlugin(ctx context.Context, arg FindActivePluginParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, findActivePlugin, arg.PluginID, arg.WorkspaceID)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.WorkspaceID,
		&i.Type,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Source,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findPluginTool = `-- name: FindPluginTool :one
SELECT id,plugin_id,tool_id,workspace_id,status,enabled,test_status,name,description,config,api_schema,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM tool WHERE plugin_id=$1 AND tool_id=$2 AND workspace_id=$3 LIMIT 1
`

type FindPluginToolParams struct {
	PluginID    string `json:"plugin_id"`
	ToolID      string `json:"tool_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindPluginTool(ctx context.Context, arg FindPluginToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, findPluginTool, arg.PluginID, arg.ToolID, arg.WorkspaceID)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ToolID,
		&i.WorkspaceID,
		&i.Status,
		&i.Enabled,
		&i.TestStatus,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.ApiSchema,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findPluginToolByID = `-- name: FindPluginToolByID :one
SELECT id,plugin_id,tool_id,workspace_id,status,enabled,test_status,name,description,config,api_schema,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM tool WHERE tool_id=$1 AND workspace_id=$2 LIMIT 1
`

type FindPluginToolByIDParams struct {
	ToolID      string `json:"tool_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindPluginToolByID(ctx context.Context, arg FindPluginToolByIDParams) (Tool, error) {
	row := q.db.QueryRow(ctx, findPluginToolByID, arg.ToolID, arg.WorkspaceID)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ToolID,
		&i.WorkspaceID,
		&i.Status,
		&i.Enabled,
		&i.TestStatus,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.ApiSchema,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActivePlugins = `-- name: ListActivePlugins :many
SELECT id,plugin_id,workspace_id,type,status,name,description,config,source,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM plugin WHERE workspace_id=$1 AND ($2::text='' OR name ILIKE '%' || $2::text || '%') AND ($3::smallint < 0 OR status=$3) AND status<>0 ORDER BY gmt_modified DESC
`

type ListActivePluginsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     int16  `json:"column_3"`
}

func (q *Queries) ListActivePlugins(ctx context.Context, arg ListActivePluginsParams) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listActivePlugins, arg.WorkspaceID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.WorkspaceID,
			&i.Type,
			&i.Status,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Source,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginTools = `-- name: ListPluginTools :many
SELECT id,plugin_id,tool_id,workspace_id,status,enabled,test_status,name,description,config,api_schema,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM tool WHERE plugin_id=$1 AND workspace_id=$2 AND ($3::text='' OR name ILIKE '%' || $3::text || '%') ORDER BY gmt_modified DESC
`

type ListPluginToolsParams struct {
	PluginID    string `json:"plugin_id"`
	WorkspaceID string `json:"workspace_id"`
	Column3     string `json:"column_3"`
}

func (q *Queries) ListPluginTools(ctx context.Context, arg ListPluginToolsParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listPluginTools, arg.PluginID, arg.WorkspaceID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.ToolID,
			&i.WorkspaceID,
			&i.Status,
			&i.Enabled,
			&i.TestStatus,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.ApiSchema,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginToolsByIDs = `-- name: ListPluginToolsByIDs :many
SELECT id,plugin_id,tool_id,workspace_id,status,enabled,test_status,name,description,config,api_schema,gmt_create,gmt_modified,creator,modifier,tenant_id
FROM tool WHERE workspace_id=$1 AND tool_id = ANY($2::text[]) ORDER BY gmt_modified DESC
`

type ListPluginToolsByIDsParams struct {
	WorkspaceID string   `json:"workspace_id"`
	Column2     []string `json:"column_2"`
}

func (q *Queries) ListPluginToolsByIDs(ctx context.Context, arg ListPluginToolsByIDsParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listPluginToolsByIDs, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.ToolID,
			&i.WorkspaceID,
			&i.Status,
			&i.Enabled,
			&i.TestStatus,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.ApiSchema,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlugin = `-- name: UpdatePlugin :exec
UPDATE plugin SET type=$3,status=$4,name=$5,description=$6,config=$7,source=$8,gmt_modified=$9,modifier=$10
WHERE plugin_id=$1 AND workspace_id=$2 AND status<>0
`

type UpdatePluginParams struct {
	PluginID    string           `json:"plugin_id"`
	WorkspaceID string           `json:"workspace_id"`
	Type        string           `json:"type"`
	Status      int16            `json:"status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      pgtype.Text      `json:"config"`
	Source      string           `json:"source"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdatePlugin(ctx context.Context, arg UpdatePluginParams) error {
	_, err := q.db.Exec(ctx, updatePlugin,
		arg.PluginID,
		arg.WorkspaceID,
		arg.Type,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Source,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updatePluginTool = `-- name: UpdatePluginTool :exec
UPDATE tool SET status=$4,enabled=$5,test_status=$6,name=$7,description=$8,config=$9,api_schema=$10,gmt_modified=$11,modifier=$12
WHERE plugin_id=$1 AND tool_id=$2 AND workspace_id=$3
`

type UpdatePluginToolParams struct {
	PluginID    string           `json:"plugin_id"`
	ToolID      string           `json:"tool_id"`
	WorkspaceID string           `json:"workspace_id"`
	Status      int16            `json:"status"`
	Enabled     int16            `json:"enabled"`
	TestStatus  int16            `json:"test_status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      string           `json:"config"`
	ApiSchema   string           `json:"api_schema"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdatePluginTool(ctx context.Context, arg UpdatePluginToolParams) error {
	_, err := q.db.Exec(ctx, updatePluginTool,
		arg.PluginID,
		arg.ToolID,
		arg.WorkspaceID,
		arg.Status,
		arg.Enabled,
		arg.TestStatus,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ApiSchema,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
