// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countModelsByProviderAndWorkspace = `-- name: CountModelsByProviderAndWorkspace :one
SELECT COUNT(*)::bigint
FROM model
WHERE provider = $1 AND workspace_id = $2
`

type CountModelsByProviderAndWorkspaceParams struct {
	Provider    string      `json:"provider"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) CountModelsByProviderAndWorkspace(ctx context.Context, arg CountModelsByProviderAndWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countModelsByProviderAndWorkspace, arg.Provider, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProvider = `-- name: CreateProvider :exec
INSERT INTO provider (
    workspace_id, icon, name, description, provider, enable, source, credential,
    supported_model_types, protocol, gmt_create, gmt_modified, creator, modifier, tenant_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateProviderParams struct {
	WorkspaceID         pgtype.Text      `json:"workspace_id"`
	Icon                pgtype.Text      `json:"icon"`
	Name                pgtype.Text      `json:"name"`
	Description         pgtype.Text      `json:"description"`
	Provider            string           `json:"provider"`
	Enable              pgtype.Int2      `json:"enable"`
	Source              string           `json:"source"`
	Credential          pgtype.Text      `json:"credential"`
	SupportedModelTypes pgtype.Text      `json:"supported_model_types"`
	Protocol            pgtype.Text      `json:"protocol"`
	GmtCreate           pgtype.Timestamp `json:"gmt_create"`
	GmtModified         pgtype.Timestamp `json:"gmt_modified"`
	Creator             pgtype.Text      `json:"creator"`
	Modifier            pgtype.Text      `json:"modifier"`
	TenantID            pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) error {
	_, err := q.db.Exec(ctx, createProvider,
		arg.WorkspaceID,
		arg.Icon,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Enable,
		arg.Source,
		arg.Credential,
		arg.SupportedModelTypes,
		arg.Protocol,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	return err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM provider
WHERE provider = $1 AND workspace_id = $2
`

type DeleteProviderParams struct {
	Provider    string      `json:"provider"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) error {
	_, err := q.db.Exec(ctx, deleteProvider, arg.Provider, arg.WorkspaceID)
	return err
}

const findProviderByCodeAndWorkspace = `-- name: FindProviderByCodeAndWorkspace :one
SELECT id, workspace_id, icon, name, description, provider, enable, source, credential,
       supported_model_types, protocol, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM provider
WHERE provider = $1 AND workspace_id = $2
LIMIT 1
`

type FindProviderByCodeAndWorkspaceParams struct {
	Provider    string      `json:"provider"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

func (q *Queries) FindProviderByCodeAndWorkspace(ctx context.Context, arg FindProviderByCodeAndWorkspaceParams) (Provider, error) {
	row := q.db.QueryRow(ctx, findProviderByCodeAndWorkspace, arg.Provider, arg.WorkspaceID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Icon,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Enable,
		&i.Source,
		&i.Credential,
		&i.SupportedModelTypes,
		&i.Protocol,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listProvidersByWorkspace = `-- name: ListProvidersByWorkspace :many
SELECT id, workspace_id, icon, name, description, provider, enable, source, credential,
       supported_model_types, protocol, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM provider
WHERE workspace_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
ORDER BY id DESC
`

type ListProvidersByWorkspaceParams struct {
	WorkspaceID pgtype.Text `json:"workspace_id"`
	Column2     string      `json:"column_2"`
}

func (q *Queries) ListProvidersByWorkspace(ctx context.Context, arg ListProvidersByWorkspaceParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByWorkspace, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Icon,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Enable,
			&i.Source,
			&i.Credential,
			&i.SupportedModelTypes,
			&i.Protocol,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE provider
SET icon = $3,
    name = $4,
    description = $5,
    enable = $6,
    credential = $7,
    supported_model_types = $8,
    protocol = $9,
    gmt_modified = $10,
    modifier = $11
WHERE provider = $1 AND workspace_id = $2
`

type UpdateProviderParams struct {
	Provider            string           `json:"provider"`
	WorkspaceID         pgtype.Text      `json:"workspace_id"`
	Icon                pgtype.Text      `json:"icon"`
	Name                pgtype.Text      `json:"name"`
	Description         pgtype.Text      `json:"description"`
	Enable              pgtype.Int2      `json:"enable"`
	Credential          pgtype.Text      `json:"credential"`
	SupportedModelTypes pgtype.Text      `json:"supported_model_types"`
	Protocol            pgtype.Text      `json:"protocol"`
	GmtModified         pgtype.Timestamp `json:"gmt_modified"`
	Modifier            pgtype.Text      `json:"modifier"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.Exec(ctx, updateProvider,
		arg.Provider,
		arg.WorkspaceID,
		arg.Icon,
		arg.Name,
		arg.Description,
		arg.Enable,
		arg.Credential,
		arg.SupportedModelTypes,
		arg.Protocol,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
