// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveAPIKeysByAccountID(ctx context.Context, accountID string) (int64, error)
	CreateTokenSession(ctx context.Context, arg CreateTokenSessionParams) error
	DeleteExpiredTokenSessions(ctx context.Context, expiresAt pgtype.Timestamp) error
	FindActiveAPIKeyByEncryptedKey(ctx context.Context, apiKey string) (FindActiveAPIKeyByEncryptedKeyRow, error)
	FindActiveAPIKeyByHash(ctx context.Context, apiKeyHash pgtype.Text) (FindActiveAPIKeyByHashRow, error)
	FindActiveAccountByID(ctx context.Context, accountID string) (Account, error)
	FindActiveAccountByUsername(ctx context.Context, username string) (Account, error)
	FindActiveTokenSessionByHash(ctx context.Context, arg FindActiveTokenSessionByHashParams) (AuthTokenSession, error)
	FindDefaultWorkspaceByAccountID(ctx context.Context, accountID string) (Workspace, error)
	ListActiveAPIKeysByAccountID(ctx context.Context, arg ListActiveAPIKeysByAccountIDParams) ([]ListActiveAPIKeysByAccountIDRow, error)
	RevokeAccountTokens(ctx context.Context, arg RevokeAccountTokensParams) error
	RevokeTokenSessionByHash(ctx context.Context, tokenHash string) error
	UpdateAccountLastLogin(ctx context.Context, arg UpdateAccountLastLoginParams) error
}

var _ Querier = (*Queries)(nil)
