// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skill (skill_code,workspace_id,account_id,name,description,source,status,tags,gmt_create,gmt_modified,creator,modifier) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type CreateSkillParams struct {
	SkillCode   string           `json:"skill_code"`
	WorkspaceID string           `json:"workspace_id"`
	AccountID   pgtype.Text      `json:"account_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Source      string           `json:"source"`
	Status      int16            `json:"status"`
	Tags        pgtype.Text      `json:"tags"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     pgtype.Text      `json:"creator"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) error {
	_, err := q.db.Exec(ctx, createSkill,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Status,
		arg.Tags,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
	)
	return err
}

const createSkillVersion = `-- name: CreateSkillVersion :exec
INSERT INTO skill_version (skill_code,workspace_id,version,description,main_file_path,manifest,content_hash,storage_type,storage_bucket,storage_prefix,package_object_key,file_count,total_size_bytes,status,gmt_create,gmt_modified,creator,modifier) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
`

type CreateSkillVersionParams struct {
	SkillCode        string           `json:"skill_code"`
	WorkspaceID      string           `json:"workspace_id"`
	Version          string           `json:"version"`
	Description      pgtype.Text      `json:"description"`
	MainFilePath     string           `json:"main_file_path"`
	Manifest         pgtype.Text      `json:"manifest"`
	ContentHash      pgtype.Text      `json:"content_hash"`
	StorageType      string           `json:"storage_type"`
	StorageBucket    pgtype.Text      `json:"storage_bucket"`
	StoragePrefix    string           `json:"storage_prefix"`
	PackageObjectKey pgtype.Text      `json:"package_object_key"`
	FileCount        pgtype.Int4      `json:"file_count"`
	TotalSizeBytes   pgtype.Int8      `json:"total_size_bytes"`
	Status           int16            `json:"status"`
	GmtCreate        pgtype.Timestamp `json:"gmt_create"`
	GmtModified      pgtype.Timestamp `json:"gmt_modified"`
	Creator          pgtype.Text      `json:"creator"`
	Modifier         pgtype.Text      `json:"modifier"`
}

func (q *Queries) CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) error {
	_, err := q.db.Exec(ctx, createSkillVersion,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.Version,
		arg.Description,
		arg.MainFilePath,
		arg.Manifest,
		arg.ContentHash,
		arg.StorageType,
		arg.StorageBucket,
		arg.StoragePrefix,
		arg.PackageObjectKey,
		arg.FileCount,
		arg.TotalSizeBytes,
		arg.Status,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
	)
	return err
}

const findActiveSkill = `-- name: FindActiveSkill :one
SELECT id,skill_code,workspace_id,account_id,name,description,source,status,tags,gmt_create,gmt_modified,creator,modifier,tenant_id FROM skill WHERE skill_code=$1 AND workspace_id=$2 AND status<>0 LIMIT 1
`

type FindActiveSkillParams struct {
	SkillCode   string `json:"skill_code"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindActiveSkill(ctx context.Context, arg FindActiveSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, findActiveSkill, arg.SkillCode, arg.WorkspaceID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.SkillCode,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Status,
		&i.Tags,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findActiveSkillVersion = `-- name: FindActiveSkillVersion :one
SELECT id,skill_code,workspace_id,version,description,main_file_path,manifest,content_hash,storage_type,storage_bucket,storage_prefix,package_object_key,file_count,total_size_bytes,status,gmt_create,gmt_modified,creator,modifier,tenant_id FROM skill_version WHERE skill_code=$1 AND workspace_id=$2 AND version=$3 AND status<>0 LIMIT 1
`

type FindActiveSkillVersionParams struct {
	SkillCode   string `json:"skill_code"`
	WorkspaceID string `json:"workspace_id"`
	Version     string `json:"version"`
}

func (q *Queries) FindActiveSkillVersion(ctx context.Context, arg FindActiveSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, findActiveSkillVersion, arg.SkillCode, arg.WorkspaceID, arg.Version)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillCode,
		&i.WorkspaceID,
		&i.Version,
		&i.Description,
		&i.MainFilePath,
		&i.Manifest,
		&i.ContentHash,
		&i.StorageType,
		&i.StorageBucket,
		&i.StoragePrefix,
		&i.PackageObjectKey,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const findLatestActiveSkillVersion = `-- name: FindLatestActiveSkillVersion :one
SELECT id,skill_code,workspace_id,version,description,main_file_path,manifest,content_hash,storage_type,storage_bucket,storage_prefix,package_object_key,file_count,total_size_bytes,status,gmt_create,gmt_modified,creator,modifier,tenant_id FROM skill_version WHERE skill_code=$1 AND workspace_id=$2 AND status<>0 ORDER BY gmt_modified DESC LIMIT 1
`

type FindLatestActiveSkillVersionParams struct {
	SkillCode   string `json:"skill_code"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindLatestActiveSkillVersion(ctx context.Context, arg FindLatestActiveSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, findLatestActiveSkillVersion, arg.SkillCode, arg.WorkspaceID)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillCode,
		&i.WorkspaceID,
		&i.Version,
		&i.Description,
		&i.MainFilePath,
		&i.Manifest,
		&i.ContentHash,
		&i.StorageType,
		&i.StorageBucket,
		&i.StoragePrefix,
		&i.PackageObjectKey,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.Status,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listActiveSkills = `-- name: ListActiveSkills :many
SELECT id,skill_code,workspace_id,account_id,name,description,source,status,tags,gmt_create,gmt_modified,creator,modifier,tenant_id FROM skill WHERE workspace_id=$1 AND ($2::text='' OR name ILIKE '%' || $2::text || '%') AND ($3::smallint < 0 OR status=$3) AND status<>0 ORDER BY gmt_modified DESC
`

type ListActiveSkillsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     int16  `json:"column_3"`
}

func (q *Queries) ListActiveSkills(ctx context.Context, arg ListActiveSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listActiveSkills, arg.WorkspaceID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.SkillCode,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.Status,
			&i.Tags,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSkillDeleted = `-- name: MarkSkillDeleted :exec
UPDATE skill SET status=0,gmt_modified=$3,modifier=$4 WHERE skill_code=$1 AND workspace_id=$2 AND status<>0
`

type MarkSkillDeletedParams struct {
	SkillCode   string           `json:"skill_code"`
	WorkspaceID string           `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) MarkSkillDeleted(ctx context.Context, arg MarkSkillDeletedParams) error {
	_, err := q.db.Exec(ctx, markSkillDeleted,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const markSkillVersionsDeleted = `-- name: MarkSkillVersionsDeleted :exec
UPDATE skill_version SET status=0,gmt_modified=$3,modifier=$4 WHERE skill_code=$1 AND workspace_id=$2 AND status<>0
`

type MarkSkillVersionsDeletedParams struct {
	SkillCode   string           `json:"skill_code"`
	WorkspaceID string           `json:"workspace_id"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) MarkSkillVersionsDeleted(ctx context.Context, arg MarkSkillVersionsDeletedParams) error {
	_, err := q.db.Exec(ctx, markSkillVersionsDeleted,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skill SET name=$3,description=$4,source=$5,status=$6,tags=$7,gmt_modified=$8,modifier=$9 WHERE skill_code=$1 AND workspace_id=$2 AND status<>0
`

type UpdateSkillParams struct {
	SkillCode   string           `json:"skill_code"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Source      string           `json:"source"`
	Status      int16            `json:"status"`
	Tags        pgtype.Text      `json:"tags"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    pgtype.Text      `json:"modifier"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.Exec(ctx, updateSkill,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Status,
		arg.Tags,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}

const updateSkillVersion = `-- name: UpdateSkillVersion :exec
UPDATE skill_version SET description=$4,main_file_path=$5,manifest=$6,content_hash=$7,storage_type=$8,storage_bucket=$9,storage_prefix=$10,package_object_key=$11,file_count=$12,total_size_bytes=$13,status=$14,gmt_modified=$15,modifier=$16 WHERE skill_code=$1 AND workspace_id=$2 AND version=$3 AND status<>0
`

type UpdateSkillVersionParams struct {
	SkillCode        string           `json:"skill_code"`
	WorkspaceID      string           `json:"workspace_id"`
	Version          string           `json:"version"`
	Description      pgtype.Text      `json:"description"`
	MainFilePath     string           `json:"main_file_path"`
	Manifest         pgtype.Text      `json:"manifest"`
	ContentHash      pgtype.Text      `json:"content_hash"`
	StorageType      string           `json:"storage_type"`
	StorageBucket    pgtype.Text      `json:"storage_bucket"`
	StoragePrefix    string           `json:"storage_prefix"`
	PackageObjectKey pgtype.Text      `json:"package_object_key"`
	FileCount        pgtype.Int4      `json:"file_count"`
	TotalSizeBytes   pgtype.Int8      `json:"total_size_bytes"`
	Status           int16            `json:"status"`
	GmtModified      pgtype.Timestamp `json:"gmt_modified"`
	Modifier         pgtype.Text      `json:"modifier"`
}

func (q *Queries) UpdateSkillVersion(ctx context.Context, arg UpdateSkillVersionParams) error {
	_, err := q.db.Exec(ctx, updateSkillVersion,
		arg.SkillCode,
		arg.WorkspaceID,
		arg.Version,
		arg.Description,
		arg.MainFilePath,
		arg.Manifest,
		arg.ContentHash,
		arg.StorageType,
		arg.StorageBucket,
		arg.StoragePrefix,
		arg.PackageObjectKey,
		arg.FileCount,
		arg.TotalSizeBytes,
		arg.Status,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
