// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tool (plugin_id, tool_id, workspace_id, status, enabled, test_status, name, description, config, api_schema, gmt_create, gmt_modified, creator, modifier, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id
`

type CreateToolParams struct {
	PluginID    string           `json:"plugin_id"`
	ToolID      string           `json:"tool_id"`
	WorkspaceID string           `json:"workspace_id"`
	Status      int16            `json:"status"`
	Enabled     int16            `json:"enabled"`
	TestStatus  int16            `json:"test_status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      string           `json:"config"`
	ApiSchema   string           `json:"api_schema"`
	GmtCreate   pgtype.Timestamp `json:"gmt_create"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Creator     string           `json:"creator"`
	Modifier    string           `json:"modifier"`
	TenantID    pgtype.Int8      `json:"tenant_id"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.PluginID,
		arg.ToolID,
		arg.WorkspaceID,
		arg.Status,
		arg.Enabled,
		arg.TestStatus,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ApiSchema,
		arg.GmtCreate,
		arg.GmtModified,
		arg.Creator,
		arg.Modifier,
		arg.TenantID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTool = `-- name: DeleteTool :exec
DELETE FROM tool WHERE id = $1 AND workspace_id = $2
`

type DeleteToolParams struct {
	ID          int64  `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteTool(ctx context.Context, arg DeleteToolParams) error {
	_, err := q.db.Exec(ctx, deleteTool, arg.ID, arg.WorkspaceID)
	return err
}

const findToolByIDAndWorkspace = `-- name: FindToolByIDAndWorkspace :one
SELECT id, plugin_id, tool_id, workspace_id, status, enabled, test_status, name, description, config, api_schema, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM tool WHERE id = $1 AND workspace_id = $2 LIMIT 1
`

type FindToolByIDAndWorkspaceParams struct {
	ID          int64  `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindToolByIDAndWorkspace(ctx context.Context, arg FindToolByIDAndWorkspaceParams) (Tool, error) {
	row := q.db.QueryRow(ctx, findToolByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ToolID,
		&i.WorkspaceID,
		&i.Status,
		&i.Enabled,
		&i.TestStatus,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.ApiSchema,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}

const listToolsByWorkspace = `-- name: ListToolsByWorkspace :many
SELECT id, plugin_id, tool_id, workspace_id, status, enabled, test_status, name, description, config, api_schema, gmt_create, gmt_modified, creator, modifier, tenant_id
FROM tool
WHERE workspace_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR plugin_id = $3::text)
ORDER BY gmt_modified DESC
`

type ListToolsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     string `json:"column_3"`
}

func (q *Queries) ListToolsByWorkspace(ctx context.Context, arg ListToolsByWorkspaceParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listToolsByWorkspace, arg.WorkspaceID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.ToolID,
			&i.WorkspaceID,
			&i.Status,
			&i.Enabled,
			&i.TestStatus,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.ApiSchema,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Creator,
			&i.Modifier,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :exec
UPDATE tool
SET plugin_id = $3, status = $4, enabled = $5, test_status = $6, name = $7, description = $8,
    config = $9, api_schema = $10, gmt_modified = $11, modifier = $12
WHERE id = $1 AND workspace_id = $2
`

type UpdateToolParams struct {
	ID          int64            `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	PluginID    string           `json:"plugin_id"`
	Status      int16            `json:"status"`
	Enabled     int16            `json:"enabled"`
	TestStatus  int16            `json:"test_status"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      string           `json:"config"`
	ApiSchema   string           `json:"api_schema"`
	GmtModified pgtype.Timestamp `json:"gmt_modified"`
	Modifier    string           `json:"modifier"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) error {
	_, err := q.db.Exec(ctx, updateTool,
		arg.ID,
		arg.WorkspaceID,
		arg.PluginID,
		arg.Status,
		arg.Enabled,
		arg.TestStatus,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ApiSchema,
		arg.GmtModified,
		arg.Modifier,
	)
	return err
}
