// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"
)

const findDefaultWorkspaceByAccountID = `-- name: FindDefaultWorkspaceByAccountID :one
SELECT id, workspace_id, account_id, status, name, description, config,
       gmt_create, gmt_modified, creator, modifier, tenant_id
FROM workspace
WHERE account_id = $1 AND status <> 0
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) FindDefaultWorkspaceByAccountID(ctx context.Context, accountID string) (Workspace, error) {
	row := q.db.QueryRow(ctx, findDefaultWorkspaceByAccountID, accountID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Creator,
		&i.Modifier,
		&i.TenantID,
	)
	return i, err
}
