authority:
  users:
    - user: openclaw@%
      password: openclaw123
    - user: root@%
      password: root123456
  privilege:
    type: ALL_PERMITTED

props:
  sql-show: true
  proxy-frontend-database-protocol-type: MySQL
